Use stdint.h instead of limits.h for UINT*_MAX definitions
While Solaris allows either one, C99 only requires them in stdint.h
and some platforms don't include them via limits.h

Corrects tinderbox reported errors on Fedora 11 build machine:

http://tinderbox.x.org/builds/2010-05-06-0019/logs/libXdmcp/#build

AA32.c: In function 'XdmcpAllocARRAY32':
AA32.c:47: error: 'UINT8_MAX' undeclared (first use in this function)

AA8.c: In function 'XdmcpAllocARRAY8':
AA8.c:47: error: 'UINT16_MAX' undeclared (first use in this function)

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>

Compiles clean on GNU/Linux AMD64
Tested-by: Gaetan Nadon <memsize@videotron.ca>