Fix build on Solaris 11.3.0 - 11.3.8
Solaris 11.3.0  added getentropy() to libc and <sys/random.h>
Solaris 11.3.9  added arc4random() to libc and <stdlib.h>
Solaris 11.4.16 added getentropy() to <stdlib.h>

So when building on Solaris releases from 11.3.0 to 11.3.8, libXdmcp
would not find arc4random(), and thus fallback to using getentropy(),
but was only looking for it in <stdlib.h>, resulting in a build error:

Key.c: In function ‘arc4random_buf’:
Key.c:86:5: error: implicit declaration of function ‘getentropy’ [-Werror=implicit-function-declaration]
     ret = getentropy (auth, len);
     ^

Reported-by: https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=54628

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>